# build.yaml для Miryoku ZMK
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: |
      -DMIRYOKU_ALPHAS=QWERTY
      -DMIRYOKU_EXTRA=COLEMAKDH
      -DMIRYOKU_TAP=QWERTY
      -DMIRYOKU_NAV=VI
      -DMIRYOKU_CLIPBOARD=MAC
      -DCONFIG_ZMK_DISPLAY=y
      -DCONFIG_ZMK_SLEEP=y
      -DCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
      -DCONFIG_ZMK_WIDGET_LAYER_STATUS=y
      -DCONFIG_ZMK_WIDGET_BATTERY_STATUS=y
      -DCONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
      -DCONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
      -DCONFIG_ZMK_WIDGET_WPM_STATUS=y
      -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
      -DCONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y
      -DCONFIG_ZMK_KEYBOARD_NAME="Anton's Chocofi"
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    cmake-args: |
      -DMIRYOKU_ALPHAS=QWERTY
      -DMIRYOKU_EXTRA=COLEMAKDH
      -DMIRYOKU_TAP=QWERTY
      -DMIRYOKU_NAV=VI
      -DMIRYOKU_CLIPBOARD=MAC
      -DCONFIG_ZMK_DISPLAY=y
      -DCONFIG_ZMK_SLEEP=y
      -DCONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
      -DCONFIG_ZMK_WIDGET_LAYER_STATUS=y
      -DCONFIG_ZMK_WIDGET_BATTERY_STATUS=y
      -DCONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
      -DCONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
      -DCONFIG_ZMK_WIDGET_WPM_STATUS=y
      -DCONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
      -DCONFIG_ZMK_DISPLAY_WORK_QUEUE_SYSTEM=y
      -DCONFIG_ZMK_KEYBOARD_NAME="Anton's Chocofi"
  - board: nice_nano_v2
    shield: settings_reset
