# build.yaml для Miryoku ZMK с Nice!View дисплеем
include:
  # Левая половина клавиатуры
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: |
      -DMIRYOKU_ALPHAS=QWERTY
      -DMIRYOKU_EXTRA=COLEMAKDH
      -DMIRYOKU_TAP=QWERTY
      -DMIRYOKU_NAV=VI
      -DMIRYOKU_CLIPBOARD=MAC
  
  # Правая половина клавиатуры
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    cmake-args: |
      -DMIRYOKU_ALPHAS=QWERTY
      -DMIRYOKU_EXTRA=COLEMAKDH
      -DMIRYOKU_TAP=QWERTY
      -DMIRYOKU_NAV=VI
      -DMIRYOKU_CLIPBOARD=MAC
  
  # Сброс настроек
  - board: nice_nano_v2
    shield: settings_reset
